apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mininnboks
  namespace: personoversikt
  cluster: prod-sbs
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 8080
  team: personoversikt
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  webproxy: true
  ingresses:
    - https://mininnboks.nav.no
    - https://mininnboks.nais.oera.no
    - https://tjenester.nav.no/mininnboks
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmininnboks-sbs
        mountPath: /var/run/secrets/nais.io/srvmininnboks
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APP_NAME
      value: "mininnboks"
    - name: APP_VERSION
      value: "{{version}}"
    - name: APP_ENVIRONMENT
      value: "p"
    - name: PUBLIC_NAMESPACE
      value: "p"
    - name: APPRES_CMS_URL
      value: "https://appres.nav.no"
    - name: SAKSOVERSIKT_LINK_URL
      value: "https://tjenester.nav.no/saksoversikt"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: MININNBOKS_URL
      value: "https://mininnboks.nav.no"
    - name: MININNBOKS_API_URL
      value: "http://mininnboks-api.personoversikt.svc.nais.local"
    - name: FRONTENDLOGGER_URL
      value: "http://frontendlogger.default.svc.nais.local"
    - name: PUBLIC_SF_DIALOG_URL
      value: "https://innboks.nav.no/"