apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mininnboks
  namespace: {{ namespace }}
  cluster: dev-sbs
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 8080
  team: personoversikt
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  webproxy: true
  ingresses:
    {{#each ingresses}}
     - {{this}}
    {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmininnboks-sbs
        mountPath: /var/run/secrets/nais.io/srvmininnboks
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APP_NAME
      value: "mininnboks"
    - name: APP_VERSION
      value: "{{version}}"
    - name: APP_ENVIRONMENT
      value: {{namespace}}
    - name: PUBLIC_NAMESPACE
      value: "{{namespace}}"
    - name: APPRES_CMS_URL
      value: "https://dekoratoren.dev.nav.no"
    - name: SAKSOVERSIKT_LINK_URL
      value: "https://tjenester-{{ namespace }}.nav.no/saksoversikt"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: MININNBOKS_URL
      value: "https://mininnboks.dev.nav.no"
