apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mininnboks
  namespace: {{ namespace }}
  cluster: dev-sbs
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 8080
  team: personoversikt
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3000m
      memory: 1024Mi
  webproxy: true
  ingresses:
    {{#each ingresses}}
     - {{this}}
    {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmininnboks-sbs
        mountPath: /var/run/secrets/nais.io/srvmininnboks
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: APP_NAME
      value: "mininnboks"
    - name: APP_VERSION
      value: "{{version}}"
    - name: APPRES_CMS_URL
      value: "https://appres-{{ namespace }}.nav.no"
    - name: SAKSOVERSIKT_LINK_URL
      value: "https://tjenester-{{ namespace }}.nav.no/saksoversikt"
    - name: AAD_B2C_CLIENTID_USERNAME
      value: "0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: AAD_B2C_DISCOVERY_URL
      value: "https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1"
    - name: MININNBOKS_URL
      value: "https://mininnboks-q.nav.no"
    - name: APP_ENVIRONMENT
      value: {{namespace}}
