export const MeldingsTyper = {
    SPORSMAL_SKRIFTLIG: 'SPORSMAL_SKRIFTLIG',
    SPORSMAL_SKRIFTLIG_DIREKTE: 'SPORSMAL_SKRIFTLIG_DIREKTE',
    SVAR_SKRIFTLIG: 'SVAR_SKRIFTLIG',
    DELVIS_SVAR: 'DELVIS_SVAR_SKRIFTLIG'
};
